"""batting: remove unique key from player

Revision ID: 22d5b8238e22
Revises: 9c2ac79463c3
Create Date: 2019-10-27 13:33:13.873851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d5b8238e22'
down_revision = '9c2ac79463c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_batting_player', table_name='batting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_batting_player', 'batting', ['player'], unique=True)
    # ### end Alembic commands ###
