"""Added bowling and fielding tables

Revision ID: 36327b473897
Revises: 22d5b8238e22
Create Date: 2019-10-27 13:41:44.087904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36327b473897'
down_revision = '22d5b8238e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bowling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=64), nullable=True),
    sa.Column('span', sa.String(length=10), nullable=True),
    sa.Column('matches', sa.String(length=6), nullable=True),
    sa.Column('innings', sa.String(length=6), nullable=True),
    sa.Column('balls', sa.String(length=6), nullable=True),
    sa.Column('runs', sa.String(length=6), nullable=True),
    sa.Column('wickets', sa.String(length=6), nullable=True),
    sa.Column('best', sa.String(length=6), nullable=True),
    sa.Column('ave', sa.String(length=6), nullable=True),
    sa.Column('econ', sa.String(length=6), nullable=True),
    sa.Column('sr', sa.String(length=6), nullable=True),
    sa.Column('four', sa.String(length=6), nullable=True),
    sa.Column('five', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fielding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=64), nullable=True),
    sa.Column('span', sa.String(length=10), nullable=True),
    sa.Column('dismissals', sa.String(length=6), nullable=True),
    sa.Column('catches', sa.String(length=6), nullable=True),
    sa.Column('stumpings', sa.String(length=6), nullable=True),
    sa.Column('catch_wk', sa.String(length=6), nullable=True),
    sa.Column('catch_fi', sa.String(length=6), nullable=True),
    sa.Column('best', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fielding')
    op.drop_table('bowling')
    # ### end Alembic commands ###
