"""Added chosen_player table

Revision ID: 42785503b566
Revises: 1a068f69755c
Create Date: 2019-10-30 16:39:40.909112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42785503b566'
down_revision = '1a068f69755c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chosen_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['fielding.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chosen_player')
    # ### end Alembic commands ###
