"""batting table

Revision ID: 4769c6625a44
Revises: f322a9f3f20e
Create Date: 2019-10-27 00:16:30.378839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4769c6625a44'
down_revision = 'f322a9f3f20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=64), nullable=True),
    sa.Column('span', sa.String(length=10), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('innings', sa.Integer(), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('hs', sa.String(length=6), nullable=True),
    sa.Column('ave', sa.Float(), nullable=True),
    sa.Column('bf', sa.Integer(), nullable=True),
    sa.Column('sr', sa.Float(), nullable=True),
    sa.Column('hundreds', sa.Integer(), nullable=True),
    sa.Column('fifties', sa.Integer(), nullable=True),
    sa.Column('ducks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batting_player'), 'batting', ['player'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batting_player'), table_name='batting')
    op.drop_table('batting')
    # ### end Alembic commands ###
