"""batting: changed all columns to String

Revision ID: 9c2ac79463c3
Revises: b931414d7675
Create Date: 2019-10-27 13:31:16.765687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c2ac79463c3'
down_revision = 'b931414d7675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batting', 'bf',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('batting', 'ducks',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('batting', 'fifties',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('batting', 'hundreds',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('batting', 'innings',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('batting', 'matches',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('batting', 'no',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('batting', 'runs',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batting', 'runs',
               existing_type=sa.String(length=6),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('batting', 'no',
               existing_type=sa.String(length=6),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('batting', 'matches',
               existing_type=sa.String(length=6),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('batting', 'innings',
               existing_type=sa.String(length=6),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('batting', 'hundreds',
               existing_type=sa.String(length=6),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('batting', 'fifties',
               existing_type=sa.String(length=6),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('batting', 'ducks',
               existing_type=sa.String(length=6),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('batting', 'bf',
               existing_type=sa.String(length=6),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
