"""batting: changed datatype of some attributes

Revision ID: b931414d7675
Revises: 4769c6625a44
Create Date: 2019-10-27 13:25:38.679172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b931414d7675'
down_revision = '4769c6625a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batting', 'ave',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('batting', 'sr',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batting', 'sr',
               existing_type=sa.String(length=6),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('batting', 'ave',
               existing_type=sa.String(length=6),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
