"""feilding: Extended size of best column

Revision ID: eaf3c367561f
Revises: 36327b473897
Create Date: 2019-10-27 13:56:18.011416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaf3c367561f'
down_revision = '36327b473897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fielding', 'best',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fielding', 'best',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###
